.TH NRM 1:LOCAL 
.ad b
.SH NAME
nrm, urm  \- recoverably remove and restore files 
.SH SYNOPSIS
.B nrm
[
.B \-f
] [
.B \-i
] [
.B \-r
] [
.B \-s
] [
.B \-t gracetime
] file ...
.br
.B urm
[
.B \-f
] file ...
.PP
.SH DESCRIPTION
.I Nrm\^
is a local replacement for \f3rm\fP(1).
Files of name "\f3dirpath/basename\fP" are 
recursively moved
to "\f3dirpath/.gone/basename\fP"
rendering them normally invisible except by \f3ls -a\fP.
Such files are also implicitly marked for future deletion by
updating their access time.
.PP
No error messages are printed when the
.B \-f
option is given
or if the standard input is not a terminal.
.PP
If a designated file is a directory,
an error comment is printed unless the optional
argument
.B \-r
has been used.
In that case,
.I nrm\^
renames the directory, making it invisible and subject to
future deletion. 
.PP
If the
.B \-i
(interactive) option is in effect,
.I nrm\^
asks whether to move each file
and, under
.BR \-r ,
whether to rename each directory.
.PP
Files are kept a default of
3 
days before permanent
deletion.  
If the 
.B [\-t gracetime] 
option is given then the file will not be permanently deleted for
at least 
.B gracetime
days, unless the file is accessed during that time.
Reading an nrm'd file will update its access time,
thereby resetting its scheduled deletion date
to be the default number of days
(3)
in the future.
.PP
If the
.B \-s
(sequenced backup) option is given,
.I nrm\^
will not overwrite saved entries in the "\f3/.gone\fP" directory,
but instead will save each file with a unique suffix such that every
deleted file is preserved for the full
.B gracetime
number of days.
.PP
On long-filename systems, the suffix is of the form:
"-YEAR-MONTH-DAY-HOUR:MIN:SEC", where each named field is 2 characters long:
eg., "foo-93-05-09-21:32:17".  If two files of the same name are
deleted within the same second (thereby potentially mapping to the same
name), the conflict is avoided by adding a random string to the conflicting
name.  The disambiguating string is of the form: "%xx" where "x" is randomly
chosen from the set "[0-9A-Za-z]". Eg., "foo-93-05-09-21:32:17%fQ".
.PP
On short-filename systems (limited to filenames of 14 characters), the 
name of the deleted file is constructed by truncating the original name
to 11 characters, and appending a random suffix of the form "%xx", as described
above.  Deleting the file "ThisIsALongFilename", with 
.B \-s
sequencing, could create the deleted file "ThisIsALong%8c".
.PP
.I Urm\^
is used to restore deleted files or directories.
Given "\f3dirpath/basename\fP" or 
"\f3dirpath/.gone/basename\fP" as an argument
.I urm\^
will search for "\f3dirpath/.gone/basename\fP"
and restore the file or directory if found.
The second form allows the user to give a command of the form
"\f3urm foo/bar/.gone/*\fP" and have the shell
do wild-card expansion.
The modification time 
of restored files is preserved.
.PP
.I Urm\^
will ask before overwriting an existing file unless the 
.B \-f 
option is in effect.
.SH FEATURES
.I Nrm\^ 
does not use \f3system\fP(2) or \f3exec\fP(2) so is significantly
faster than similiar script-based implementations. 
.PP
.I Nrm\^
works over RFA.
.PP
When updating system executable files, using
.I nrm\^ 
to remove the old file will prevent causing a
"killed on text modification" swap error.
The removed version will be permanently deleted
.B gracetime
days after the last process has ceased to
swap to the removed file.
.PP
This renaming strategy was used to  give a good summary 
when using \f3du\fP(1) to evaluate freed-up disk space. 
.SH ADMINISTRATION
A line like the following should be added 
to root's crontab:
.br
.nf

	30 1 * * *		/etc/nrm.cleanup

.fi
.br
The nrm.cleanup script permanently removes all 
empty directories and expired files. 
.SH SEE ALSO
rm(1) unlink(2).
.SH DIAGNOSTICS
Generally self-explanatory.
An attempt was made to provide the same exit codes 
and user interface as \f3rm\fP.
Returns 0 if successful, 2 on
errors.
It is forbidden to remove the file "\f3..\fP",
the file "\f3.\fP" and the
files "\f3.gone/*\fP".  The  
.B \-t
option does not work on symbolic links.
.PP
.SH AUTHOR
Rick Walker (walker@hpl-opus.hpl.hp.com)
